[package]
name = "intelligent-file-deduplicator"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
hex = "0.4"
rayon = "1.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1.10"